# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - working_branch  # Change as needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: |
    dotnet restore
    dotnet build --configuration Release
    dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/wwwroot
  displayName: 'Build and Publish Blazor WASM'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/wwwroot'
    artifactName: 'drop'
    publishLocation: 'Container'

