name: Build and Deploy Blazor WASM to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Update if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Blazor WASM
        run: dotnet build --configuration Release --no-restore

      - name: Publish Blazor WASM
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: wasm-app
          path: ./publish/wwwroot

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: wasm-app

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FolsomOT'  # Replace with your Azure App Service name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
